###
GET http://localhost:9090/ping
Accept: application/json

###
POST http://localhost:9090/ping/kevin
Accept: application/json
Content-Type: application/json

{
    "message": "Hello"
}

###
GET http://localhost:9090/v1/coronavirus/sync/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/async/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/caching/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/resilient/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9091/actuator/info
Accept: application/json

###
GET http://localhost:9091/actuator/health
Accept: application/json

###
GET http://localhost:9091/actuator/prometheus
Accept: text/plain

###
GET http://localhost:9090/secure/ping
Accept: application/json
Authorization: Bearer TODO

###
GET http://localhost:9090/todos
Accept: application/json

###
POST http://localhost:9090/todos
Accept: application/json
Content-Type: application/json

{
    "title": "Shopping",
    "tasks": [
        {
            "description": "Milk"
        },
        {
            "description": "Eggs"
        }
    ]
}