###
GET http://localhost:9090/ping
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/sync/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/async/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9090/v1/coronavirus/caching/new-cases-by-publish-date
Accept: application/json

###
GET http://localhost:9091/actuator/info
Accept: application/json

###
GET http://localhost:9091/actuator/health
Accept: application/json

###
GET http://localhost:9091/actuator/prometheus
Accept: text/plain
