server:
  port: 9090
management:
  server:
    port: 9091
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  info:
    build:
      enabled: true

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      use-big-decimal-for-floats: true
    serialization:
      indent-output: false

coronavirus:
  base-url: https://api.coronavirus.data.gov.uk
