server:
  port: 9090
management:
  server:
    port: 9091
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  info:
    build:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

spring:
  datasource:
    embedded-database-connection: h2
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      use-big-decimal-for-floats: true
    serialization:
      indent-output: false

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG

coronavirus:
  base-url: https://api.coronavirus.data.gov.uk

resilience4j:
  circuitbreaker:
    instances:
      covid:
        registerHealthIndicator: true
        slidingWindowSize: 100
